replicaCount: 1

image:
  repository: ghcr.io/arntbergin/kulturbotten
  tag: "0.4"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: true
  host: kulturbot.bergin.no
